# Generated by Django 3.2.3 on 2021-05-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20210527_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
